# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: name-tests-test
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
